# Generated by Django 3.0.6 on 2020-06-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20200621_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(height_field=300, upload_to='photoGallery/', width_field=300),
        ),
    ]
