# Generated by Django 3.0.6 on 2020-06-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20200623_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(default='DESCRIPTION', max_length=100),
        ),
    ]
